apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
  namespace: dockube
spec:
  selector:
    matchLabels:
      app: sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
      - name: kartik
        image: mittalkartik87/dockube:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: kartik
          containerPort: 90
      
      - name: arpita
        image: arpitagupta19/dockube_final:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: arpita
          containerPort: 1050

      - name: sagnik
        image: sagnikr/dockube-sagnik
        imagePullPolicy: IfNotPresent
        ports:
        - name: sagnik
          containerPort: 5000
      
      - name: sanchita
        image: sanchitaagnihotri/dockube_sanchita:sanchita_app_push
        imagePullPolicy: IfNotPresent
        ports:
        - name: sanchita
          containerPort: 2000

---

apiVersion: v1
kind: Service
metadata:
  name: sidecar
  namespace: dockube
spec:
  type: 
  selector:
    app: sidecar
  ports:
    - protocol: "TCP"
      name: kartik
      port: 90
      targetPort: kartik
    - protocol: "TCP"
      name: arpita
      port: 1050
      targetPort: arpita    
    - protocol: "TCP"
      name: sagnik
      port: 5000
      targetPort: sagnik
    - protocol: "TCP"
      name: sanchita
      port: 2000
      targetPort: sanchita
